# Generated by Django 5.2.3 on 2025-07-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
