# Generated by Django 5.2.3 on 2025-07-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdetails_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='job_title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
