# Generated by Django 5.2.3 on 2025-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdetails_created_at_alter_userdetails_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedresume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='generatedresume',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='generatedresume',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='generatedresume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user_name',
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='github_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='is_working_here',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='linkdin_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='pincode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='website_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='work_background_titel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='work_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='work_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='work_job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='work_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='your_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
