# Generated by Django 5.2.3 on 2025-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_generatedresume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='experiance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
