# Generated by Django 5.2.3 on 2025-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_generatedresume_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='school_passing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
