# Generated by Django 5.2.3 on 2025-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_generatedresume_school_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='collage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
