# Generated by Django 5.2.3 on 2025-07-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_generatedresume_collage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedresume',
            old_name='work_background_titel',
            new_name='work_background_title',
        ),
    ]
